from deepagents import create_deep_agent
from src.agents.research_agent import create_research_agent
from src.middleware import ApprovePlan
from src.prompts import PLANNER_SUB_AGENT_PROMPT, MAIN_AGENT_PROMPT
from src.schema import PlanOutput
from langchain.agents.structured_output import ToolStrategy




def create_test1_agent(model, checkpointer):

    planner_agent = {
        "name": "planner-agent",
        "description": '''Specialist planner agent with filesystem integration:
                               - Deliver a complete, slide-by-slide plan suitable for building a professional presentation
                               - Saves planning notes and structure decisions to `/notes/presentation_notes.txt`
                               - Saves draft plan structure in `/workspace/plan_draft.md`
                               - Return plan in JSON format
                               You may use this plan to generate the presentation or return the completed plan to the user.''',
        "system_prompt": """You are a Agent responsible for generating detailed, structured presentation plans (.pptx).
Your objective is to deliver a complete, slide-by-slide plan suitable for building a professional presentation.

<Task Purpose>
1. Gather information about presentation
2. Read the research findings about topic
3. Based on the information received, develop a presentation plan
4. Output final structured JSON plan
5. Revise the plan based on the user's request, if feedback provided. If there is no user feedback, save the plan.
</Task Purpose>

<Filesystem Structure - ALWAYS USE THESE EXACT PATHS>
Organize your research systematically using these files:
**WORKING FILES:**
- `/workspace/plan_draft.md` - Your working presentation outline
- `/notes/presentation_notes.txt` - Planning notes and structure decisions
</Filesystem Structure>

<Workflow Instructions>
1. Read `/research/query.txt` and obtain presentation details from the file.
2. Build detailed plan:
    -Slide number
    -Slide title
    -Slide content (bullet points or short text)
    -Recommended charts, graphs or tables (Specify type and what data they should contain)
    -Recommended images or illustrations (Provide concrete suggestions)
    -Speaker notes (Detailed, structured; what the presenter should say)
    Target minimum 6 slides (title + 5 content slides)

</Workflow Instructions>

<Output format>
Return ONLY valid JSON in this exact format (Structure only — not a real example):
{
    "title":,
    "subtitle":,
    "topic":,
    "target_audience":,
    "number_of_slides":,
    "slides": [
        {
            "slide_number": 1,
            "title": ,
            "slide_content": ,
            "key_bullet_points": [],
            "suggested images": None,
            "suggested charts": None,
            "suggested_tables": None,
            "speaker_notes":,
        },
        {
            "slide_number": 2,
            "title": "Key Point 1",
            "slide_type": "content",
            "key_bullet_points": ["Point A", "Point B", "Point C"],
            "suggested images": None,
            "suggested charts": None,
            "suggested_tables": None,
            "speaker_notes": "Explain these points..."
        }
    ],
}
</Output format>

<Quality Requirements>
- 6 slides minimum (adjust if user specifies)
- Maintain style and tone from `/research/query.txt`
- The first slide must be a title slide and contain the topic title. 
- Some slides may contain only a table, only a chart, or only an image.
- Suggest SPECIFIC chart types (bar, pie, line, flowchart)
</Quality Requirements>
""",
        "middleware": [ApprovePlan(),],
        "response_format": ToolStrategy(PlanOutput)

    }

    main_agent = create_deep_agent(
        model=model,
        system_prompt="""You are deep agent. Your purpose is to assist the user in generating detailed, structured presentation (.pptx) plans in JSON format.
You collaborate with a *planner-agent* responsible for creating a detailed presentation plan in JSON format.
<Filesystem Structure - ALWAYS USE THESE EXACT PATHS>
Organize your research systematically using these files:
**WORKING FILES:**
- `/workspace/plan_draft.md` - Working presentation outline generated by *planner-agent*
- `/notes/presentation_notes.txt` - Planning notes and structure decisions generated by *planner-agent*
</Filesystem Structure>

<Workflow Instructions>
1. **PREPARATION PHASE** - Analyze user`s query:
    -Analyze and understand: the user's intent and the specific goal
    -If the user's request involves creating a plan, presentation, text, or article, identify the topic, target audience, and desired narrative style if any details are missing, clarify them by asking the user
    -Use *write_file* for write user`s query and obtained information (helpful in research or creation tasks) such as topic, target audience, narrative style, number of slides in `/research/query.txt`
    
2. **PLANNING PHASE** - Use *planner-agent*:
    -Delegate plan-creation-task to *planner-agent*
    -Use *read_file* for read draft plan structure in `/workspace/plan_draft.md`
    -Do not try to create plan yourself! Delegate it to *planner-agent*
    
4. Return plan json plan from `/workspace/plan_draft.md` to user. Dont edit file or rewrite the plan, just return it

</Workflow Instructions>
""",
        subagents=[planner_agent],
        checkpointer=checkpointer,
    )
    return main_agent